LoaderErrors:
  apachenew:
    Core Check Loader: Check apachenew not found in Catalog
    JMX Check Loader: check is not a jmx check, or unable to determine if it's so
    Python Check Loader: 'unable to import module ''apachenew'': No module named ''apachenew'''
  kube_controller_manager:
    Core Check Loader: Check kube_controller_manager not found in Catalog
    JMX Check Loader: check is not a jmx check, or unable to determine if it's so
    Python Check Loader: |-
      could not configure check instance for python check kube_controller_manager: could not invoke 'kube_controller_manager' python check constructor. New constructor API returned:
      Traceback (most recent call last):
        File "/opt/datadog-agent/embedded/lib/python3.8/site-packages/datadog_checks/kube_controller_manager/kube_controller_manager.py", line 108, in __init__
          super(KubeControllerManagerCheck, self).__init__(
        File "/opt/datadog-agent/embedded/lib/python3.8/site-packages/datadog_checks/base/checks/openmetrics/base_check.py", line 126, in __init__
          raise CheckException(
      datadog_checks.base.errors.CheckException: The agent could connect to none of the following URL: ['https://192.168.49.2:10257/metrics', 'https://localhost:10257/metrics', 'http://192.168.49.2:10252/metrics', 'http://localhost:10252/metrics'].
      Deprecated constructor API returned:
      __init__() got an unexpected keyword argument 'agentConfig'
  kube_scheduler:
    Core Check Loader: Check kube_scheduler not found in Catalog
    JMX Check Loader: check is not a jmx check, or unable to determine if it's so
    Python Check Loader: |-
      could not configure check instance for python check kube_scheduler: could not invoke 'kube_scheduler' python check constructor. New constructor API returned:
      Traceback (most recent call last):
        File "/opt/datadog-agent/embedded/lib/python3.8/site-packages/datadog_checks/kube_scheduler/kube_scheduler.py", line 113, in __init__
          super(KubeSchedulerCheck, self).__init__(
        File "/opt/datadog-agent/embedded/lib/python3.8/site-packages/datadog_checks/base/checks/openmetrics/base_check.py", line 126, in __init__
          raise CheckException(
      datadog_checks.base.errors.CheckException: The agent could connect to none of the following URL: ['https://192.168.49.2:10259/metrics', 'https://localhost:10259/metrics', 'http://192.168.49.2:10251/metrics', 'http://localhost:10251/metrics'].
      Deprecated constructor API returned:
      __init__() got an unexpected keyword argument 'agentConfig'
RunErrors: {}